export const catalogBannerDefault = {
    "button": {
        "name": "КНОПКА",
        "model": "style",
        "active": false,
        "mobile": {
            "top": "none",
            "left": "none",
            "color": null,
            "right": "none",
            "value": "Перейти к каталогу",
            "width": "200px",
            "border": "1px solid black",
            "bottom": "none",
            "padding": "15px 20px",
            "fontSize": "16px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "500",
            "borderRadius": "10px"
        },
        "desktop": {
            "top": "none",
            "left": "none",
            "color": null,
            "right": "none",
            "value": "Перейти к каталогу",
            "width": "200px",
            "border": "1px solid black",
            "bottom": "none",
            "padding": "15px 20px",
            "fontSize": "16px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "500",
            "borderRadius": "10px"
        }
    },
    "text_one": {
        "name": "ТЕКСТ 1",
        "model": "style",
        "active": false,
        "mobile": {
            "top": "none",
            "left": "none",
            "color": "#9C2D40",
            "right": "none",
            "value": "Кожаные",
            "width": null,
            "border": "none",
            "bottom": "none",
            "padding": "10px",
            "fontSize": "60px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "600",
            "marginLeft": "none",
            "marginBottom": "-10px",
            "textTransform": "uppercase"
        },
        "desktop": {
            "top": "none",
            "left": "none",
            "color": "#9C2D40",
            "right": "none",
            "value": "Кожаные",
            "width": null,
            "border": "none",
            "bottom": "none",
            "padding": "10px",
            "fontSize": "60px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "600",
            "marginLeft": "none",
            "marginBottom": "-10px",
            "textTransform": "uppercase"
        }
    },
    "text_two": {
        "name": "ТЕКСТ 2",
        "model": "style",
        "active": false,
        "mobile": {
            "top": "none",
            "left": "20%",
            "color": null,
            "right": "none",
            "value": "аксессуары",
            "border": "none",
            "bottom": "none",
            "padding": "10px",
            "fontSize": "60px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "600",
            "marginLeft": "40px",
            "textTransform": "uppercase"
        },
        "desktop": {
            "top": "none",
            "left": "20%",
            "color": null,
            "right": "none",
            "value": "аксессуары",
            "border": "none",
            "bottom": "none",
            "padding": "10px",
            "fontSize": "60px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "600",
            "marginLeft": "40px",
            "textTransform": "uppercase"
        }
    },
    "text_four": {
        "name": "ТЕКСТ 4",
        "model": "style",
        "active": false,
        "mobile": {
            "top": "none",
            "left": "none",
            "color": null,
            "right": "none",
            "value": "Доступно выполнение индивидуальных заказов",
            "border": null,
            "bottom": "none",
            "padding": "10px",
            "fontSize": "13px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "300"
        },
        "desktop": {
            "top": "none",
            "left": "none",
            "color": null,
            "right": "none",
            "value": "Доступно выполнение индивидуальных заказов",
            "border": null,
            "bottom": "none",
            "padding": "10px",
            "fontSize": "13px",
            "position": null,
            "fontFamily": "Inter",
            "fontWeight": "300"
        }
    },
    "background": {
        "name": "ФОН БАНЕРА",
        "model": "background",
        "active": true,
        "mobile": {
            "height": "500px",
            "backgroundSize": "30%",
            "backgroundColor": "#fff9ed",
            "backgroundImage": "url('https://st2.depositphotos.com/1001046/7232/v/600/depositphotos_72327721-stock-illustration-set-of-handbags-for-all.jpg')",
            "backgroundRepeat": "no-repeat",
            "backgroundPosition": "left top",
            "padding": "20px 40px",
            "margin": "0",
        },
        "desktop": {
            "height": "500px",
            "backgroundSize": "contain",
            "backgroundColor": "#fff9ed",
            "backgroundImage": "url('https://st2.depositphotos.com/1001046/7232/v/600/depositphotos_72327721-stock-illustration-set-of-handbags-for-all.jpg')",
            "backgroundRepeat": "no-repeat",
            "backgroundPosition": "right",
            "padding": "70px 80px",
            "margin": "60px 0",

        }
    },
    "text_three": {
        "name": "ТЕКСТ 3",
        "model": "style",
        "active": false,
        "mobile": {
            "top": "none",
            "left": "20%",
            "color": null,
            "right": "none",
            "value": "ручной работы",
            "border": "none",
            "bottom": "none",
            "padding": "10px",
            "fontSize": "24px",
            "position": null,
            "fontWeight": "300",
            "marginLeft": "40px",
            "marginBottom": "30px",
            "textTransform": "uppercase"
        },
        "desktop": {
            "top": "none",
            "left": "20%",
            "color": null,
            "right": "none",
            "value": "ручной работы",
            "border": "none",
            "bottom": "none",
            "padding": "10px",
            "fontSize": "24px",
            "position": null,
            "fontWeight": "300",
            "marginLeft": "40px",
            "marginBottom": "30px",
            "textTransform": "uppercase"
        }
    },
    "button_link": {
        "name": "КНОПКА",
        "model": "style",
        "active": false,
        "mobile": "",
        "desktop": ""
    },
}
