name: ci

env:
  DEPLOY_PATH: /var/www/html/gentcman_admin/
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Deploy to ${{ env.BRANCH_NAME }}      
        run: sudo apt-get update -qq && sudo apt-get install -y -qq sshpass && sshpass -p ${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }} ssh -oStrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USERNAME }}@${{ secrets.DEPLOY_SERVER_HOST }} -p${{ secrets.DEPLOY_SERVER_PORT }} 'bash -i -c "cd ${{ env.DEPLOY_PATH }}${{ env.BRANCH_NAME }} && git stash && git checkout ${{ env.BRANCH_NAME }} && git pull origin ${{ env.BRANCH_NAME }}  && npm i && npm run build"'
      - name: Print Info
        run: echo "Deployed at https://flowery.salve.dev/"
